### ISSUE TITLE
Problems starting the app

### ISSUE THREAD

**Issue by johnpaulashenfelter** [ernie/venture#1]
Thanks for releasing this -- was excited to take a look. But I'm having problems. One is a RTFM about `the_setup` vs just running things locally :)

I changed the `appconfig.js`

   // Production hostname is determined during server-side build.
   // You'll want to change "venture.local.devel" to something like
   // "localhost:3000" if you aren't running https://github.com/ernie/the_setup
-  HOSTNAME: PRODUCTION ? process.env.HOSTNAME : 'venture.local.devel',
-  HOSTNAME: PRODUCTION ? process.env.HOSTNAME : '127.0.0.1:3000',

and then

```
mix phoenix.server
[info] Running Venture.Endpoint with Cowboy on http://localhost:3000
```

followed by `npm start` in another window

```
...
  [836] (webpack)-dev-server/client?http://localhost:8000 2.48 kB {0} [built]
  [837] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
  [838] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
  [839] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
webpack: bundle is now VALID.
```

Then I get the a page at http://localhost:8000/. Yay!

But clicking "I'm an attendee" gives me

``````
WebSocket connection to 'wss://127.0.0.1:3000/socket/websocket?vsn=1.0.0' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR```

in the JS console. Same thing for presenter mode

```WebSocket connection to 'wss://127.0.0.1:3000/socket/websocket?token=abc123&vsn=1.0.0' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR```

I'm not an elixir guy (yet) so this isn't so helpful:

``````

[error] Ranch protocol #PID<0.298.0> (:cowboy_protocol) of listener Venture.Endpoint.HTTP terminated
*\* (exit) an exception was raised:
    *\* (FunctionClauseError) no function clause matching in :cowboy_protocol.parse_method/3
        (cowboy) src/cowboy_protocol.erl:168: :cowboy_protocol.parse_method("", {:state, #Port<0.6338>, :ranch_tcp, [:cowboy_router, :cowboy_handler], false, [listener: Venture.Endpoint.HTTP, dispatch: [{:_, [], [{["socket", "longpoll"], [], Plug.Adapters.Cowboy.Handler, {Phoenix.Transports.LongPoll, {Venture.Endpoint, Venture.UserSocket, :longpoll}}}, {["socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {Venture.Endpoint, Venture.UserSocket, :websocket}}}, {:_, [], Plug.Adapters.Cowboy.Handler, {Venture.Endpoint, []}}]}]], :undefined, :undefined, 5, 1, 100, 4096, 64, 4096, 100, 5000, 1452271223246}, <<22, 3, 1, 0, 123, 1, 0, 0, 119, 3, 2, 37, 201, 215, 148, 93, 170, 226, 201, 176, 247, 69, 54, 26, 129, 47, 44, 185, 95, 151, 161, 99, 254, 255, 68, 15, 130, 167, 73, 66, 94, 102, 118, 0, 0, 28, 192, 10, 192, 20, ...>>)
[error] Process #PID<0.299.0> raised an exception
*\* (FunctionClauseError) no function clause matching in :cowboy_protocol.parse_method/3
    (cowboy) src/cowboy_protocol.erl:168: :cowboy_protocol.parse_method("", {:state, #Port<0.6339>, :ranch_tcp, [:cowboy_router, :cowboy_handler], false, [listener: Venture.Endpoint.HTTP, dispatch: [{:_, [], [{["socket", "longpoll"], [], Plug.Adapters.Cowboy.Handler, {Phoenix.Transports.LongPoll, {Venture.Endpoint, Venture.UserSocket, :longpoll}}}, {["socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {Venture.Endpoint, Venture.UserSocket, :websocket}}}, {:_, [], Plug.Adapters.Cowboy.Handler, {Venture.Endpoint, []}}]}]], :undefined, :undefined, 5, 1, 100, 4096, 64, 4096, 100, 5000, 1452271223260}, <<22, 3, 1, 0, 123, 1, 0, 0, 119, 3, 1, 154, 11, 114, 185, 3, 92, 112, 39, 157, 176, 29, 114, 7, 65, 138, 5, 142, 73, 186, 217, 178, 40, 184, 143, 204, 142, 140, 64, 166, 148, 63, 4, 0, 0, 28, 192, 10, 192, 20, ...>>)

```

Is there some simple something I'm doing incorrectly?
```

**Comment by ernie** [comment]
@johnpaulashenfelter -- first, sorry for just now responding! Oddly, GH doesn't actually make me "watch" my own repos by default, so I didn't get a notification on this message.

If you're not running any kind of SSL endpoint (which `the_setup` would have you doing) then you can't use `wss://` as your protocol. This is also settable in appconfig.js. Just change it to `ws://` instead, and you should be good to go.

Let me know if that doesn't do the trick. :)
